### ISSUE TITLE
Where is @Educational-Websites

### ISSUE THREAD

**Issue by devashish2024** [Genius398/Genius398#4]
I don't know where is @Educational-Websites gone. What happen with it?

**Comment by N3RDIUM** [comment]
Yeah! Where is it?

**Comment by N3RDIUM** [comment]
@Genius398!

**Comment by Genius398** [comment]
I deleted it

**Comment by N3RDIUM** [comment]
So we have to make it again?

**Comment by Genius398** [comment]
i made @Website-Designers

**Comment by Genius398** [comment]
join now

**Comment by somePythonProgrammer** [comment]
Please invite me.

**Comment by devashish2024** [comment]
:(

**Comment by devashish2024** [comment]
Note: There will be all our old projects required right now, So don't move them to your trash.
